In [5]:
import pandas as pd
df=pd.read_csv("urinalysis_tests.csv")
df

,Unnamed: 0,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,0,76.00,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,01-Mar,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,1,9.00,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,01-Mar,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,2,12.00,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,3,77.00,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,05-Aug,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,4,29.00,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,01-Apr,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1431,0.06,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.015,01-Feb,0-1,RARE,FEW,NONE SEEN,RARE,NEGATIVE
1432,1432,42.00,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.5,1.010,0-2,0-2,RARE,NONE SEEN,NONE SEEN,RARE,NEGATIVE
1433,1433,47.00,FEMALE,DARK YELLOW,CLEAR,NEGATIVE,TRACE,6.0,1.030,02-Apr,0-2,MODERATE,MODERATE,NONE SEEN,RARE,NEGATIVE
1434,1434,57.00,FEMALE,DARK YELLOW,CLEAR,NEGATIVE,TRACE,5.0,1.030,0-2,0-2,PLENTY,PLENTY,NONE SEEN,FEW,NEGATIVE
1435,1435,3.00,MALE,YELLOW,CLEAR,NEGATIVE,NEGATIVE,6.0,1.020,0-1,0-2,RARE,RARE,NONE SEEN,RARE,NEGATIVE

In [6]:
df.dtypes

Unnamed: 0            int64
Age                 float64
Gender               object
Color                object
Transparency         object
Glucose              object
Protein              object
pH                  float64
Specific Gravity    float64
WBC                  object
RBC                  object
Epithelial Cells     object
Mucous Threads       object
Amorphous Urates     object
Bacteria             object
Diagnosis            object
dtype: object